In [21]:
import os as os

In [22]:
directory_path = "C:/Users/MCOB PHD 14/Dropbox/Charlie's Dissertation/Beige Books"

In [23]:
text_data = []

In [24]:
# Loop through the files in the directory
for filename in os.listdir(directory_path):
    if filename.endswith(".txt"):
        with open(os.path.join(directory_path, filename), 'r', encoding='utf-8') as file:
            text_data.append(file.read())

KeyboardInterrupt:

In [ ]:
import nltk
from nltk.tokenize import word_tokenize
from collections import Counter

nltk.download('punkt')

# Initialize an empty list to store word counts for each document
word_counts = []

[nltk_data] Downloading package punkt to C:\Users\MCOB PHD
[nltk_data]     14\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [ ]:
# Tokenize and count words in each document
for document in text_data:
    tokens = word_tokenize(document)
    word_counts.append(len(tokens))

In [ ]:
import numpy as np

# Calculate summary statistics
mean_word_count = np.mean(word_counts)
median_word_count = np.median(word_counts)
max_word_count = np.max(word_counts)
min_word_count = np.min(word_counts)

print("Mean Word Count:", mean_word_count)
print("Median Word Count:", median_word_count)
print("Max Word Count:", max_word_count)
print("Min Word Count:", min_word_count)

Mean Word Count: 1100.8826072497507
Median Word Count: 1036.0
Max Word Count: 4134
Min Word Count: 15

In [ ]:
import pandas as pd
wordsDF = pd.DataFrame(word_counts, columns = ['Word_Count'])

In [ ]:
wordsDF.describe()

        Word_Count
count  6014.000000
mean   1100.882607
std     356.346939
min      15.000000
25%     857.000000
50%    1036.000000
75%    1293.000000
max    4134.000000

In [ ]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\MCOB PHD
[nltk_data]     14\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [ ]:
# Sample text data
text = text_data[0]

# Tokenize the text into words
words = nltk.word_tokenize(text)

# Remove stopwords
filtered_words = [word for word in words if word.lower() not in stopwords.words('english')]

# Join the filtered words back into a sentence (if needed)
filtered_text = ' '.join(filtered_words)
filtered_text_token = nltk.word_tokenize(filtered_text)

In [ ]:
filtered_text_token

['December',
 '9',
 ',',
 '1970',
 'economy',
 'Southeast',
 'marking',
 'time',
 '.',
 'Although',
 'layoffs',
 'continue',
 'dominate',
 'employment',
 'news',
 ',',
 'enough',
 'bright',
 'spots',
 'District',
 "'s",
 'economy',
 'keep',
 'even',
 'keel',
 '.',
 'Construction',
 'low-income',
 'housing',
 'road',
 'building',
 'active',
 ',',
 'slow',
 'steady',
 'flow',
 'announcements',
 'new',
 'plants',
 'plant',
 'expansions',
 'encouraging',
 '.',
 'soon-to-be-released',
 'survey',
 'indicates',
 'Tennessee',
 'businessmen',
 'cautiously',
 'optimistic',
 'outlook',
 '.',
 'hand',
 ',',
 'numerous',
 'announcements',
 'price',
 'increases',
 'appeared',
 '.',
 'sentiment',
 'among',
 'directors',
 'wage',
 'price',
 'controls',
 '.',
 'aluminum',
 'industry',
 'fearful',
 'may',
 'settle',
 'package',
 'similar',
 'GM',
 'contract',
 'upcoming',
 'labor',
 'negotiations',
 'spite',
 'fact',
 'industry',
 'doldrums',
 '.',
 'Aluminum',
 'exports',
 '.',
 'One',
 'large',
 'producer',
 'gradually',
 'reduced',
 'labor',
 'force',
 '6,800',
 '5,500',
 ',',
 '1,000',
 'released',
 'last',
 'year',
 '.',
 'producer',
 'New',
 'Orleans',
 'vicinity',
 'recently',
 'shut',
 'one',
 'lines',
 ',',
 'idling',
 '125',
 'aluminum',
 'workers',
 '.',
 'Layoffs',
 'also',
 'occurring',
 'industries',
 'chemical',
 ',',
 'paper',
 ',',
 'airlines',
 ',',
 'aircraft',
 '.',
 'chemical',
 'firm',
 'south',
 'Louisiana',
 'idling',
 '800',
 'employees',
 ',',
 'including',
 'administrators',
 'supervisors',
 '.',
 'north',
 'Florida',
 'paper',
 'producer',
 'temporarily',
 'cutting',
 'production—affecting',
 '680',
 'workers—and',
 'southern',
 'Mississippi',
 'paper',
 'mill',
 'gradually',
 'reducing',
 'work',
 'force',
 '.',
 'aircraft',
 'R',
 '&',
 'Center',
 'dropping',
 '300',
 'employees',
 'end',
 'year',
 '.',
 'Florida',
 ',',
 '200',
 'employees',
 'airline',
 'laid',
 'slowdown',
 'business',
 'tourist',
 'traffic',
 '.',
 'weakness',
 'job',
 'market',
 'college-educated',
 'people',
 'underscored',
 'decrease',
 'campus',
 'recruiting',
 ',',
 'especially',
 'aerospace',
 'defense-related',
 'firms',
 'Federal',
 'agencies',
 '.',
 'Newspapers',
 'District',
 'carrying',
 'reports',
 'price',
 'increases',
 ',',
 'one',
 'paper',
 'decried',
 'October',
 'increase',
 'consumer',
 'prices',
 'editorial',
 'entitled',
 '``',
 ',',
 'Away',
 '``',
 '.',
 'Papers',
 'recently',
 'highlighted',
 'price',
 'wage',
 'increases',
 'following',
 'areas',
 ':',
 'white',
 'collar',
 'wages',
 ',',
 'freight',
 'rates',
 ',',
 'proposed',
 'Atlanta',
 'bus',
 'fares',
 ',',
 'intrastate',
 'bus',
 'fares',
 'Georgia',
 ',',
 'Atlanta',
 'food',
 'prices',
 ',',
 'proposed',
 'phone',
 ',',
 'utility',
 ',',
 'milk',
 'prices',
 '.',
 'However',
 ',',
 'articles',
 'called',
 'attention',
 'lower',
 'interest',
 'rates',
 '.',
 'example',
 ',',
 'one',
 'article',
 'stated',
 'Tennessee',
 'taxpayers',
 'saved',
 '$',
 '4',
 'million',
 'interest',
 'costs',
 'lower',
 'interest',
 'rates',
 'bonds',
 '.',
 'Also',
 ',',
 'reported',
 'differences',
 'bids',
 'construction',
 'subcontractors',
 'small',
 ',',
 'indicating',
 'keen',
 'competition',
 '.',
 'sluggish',
 'pace',
 'economic',
 'activity',
 'slowed',
 'growth',
 'revenues',
 'state',
 'local',
 'governments',
 '.',
 'consequence',
 ',',
 'governments',
 'begun',
 'cut',
 'spending',
 '.',
 'example',
 ',',
 'Georgia',
 "'s",
 'budget',
 'current',
 'fiscal',
 'year',
 'based',
 'anticipated',
 'revenue',
 'increase',
 '9.5',
 'percent',
 '.',
 'November',
 'receipts',
 'ran',
 '1.3',
 'percent',
 'year-ago',
 'level',
 '.',
 'prompted',
 'cost-cutting',
 'measures',
 'areas',
 'state',
 "'s",
 'government',
 '.',
 'fire',
 'Shell',
 'Oil',
 'platform',
 'Gulf',
 'serious',
 'similar',
 'Chevron',
 'fire',
 ',',
 'wells',
 'platform',
 'prevailing',
 'currents',
 'site',
 'toward',
 'Coast',
 '.',
 'Chevron',
 'fire',
 'resulted',
 'moratorium',
 'well',
 'digging',
 'depressed',
 'economic',
 'activity',
 'along',
 'Louisiana',
 'Mississippi',
 'Gulf',
 'Coasts',
 '.',
 'likely',
 'industries',
 'localities',
 'depend',
 'upon',
 'offshore',
 'oil',
 'drilling',
 'adversely',
 'affected',
 '.',
 'bright',
 'side',
 ',',
 'production',
 'light',
 'fixtures',
 'large',
 'plant',
 'Mississippi',
 'stabilizing',
 'gradual',
 'decline',
 '.',
 'Florida',
 'outlays',
 'road',
 'construction',
 'increasing',
 'two',
 'bond',
 'issues',
 'recently',
 'received',
 'cabinet-level',
 'approval',
 '.',
 'Alabama',
 "'s",
 'expenditures',
 'roads',
 '25',
 'per',
 'cent',
 'greater',
 'year',
 'last',
 '.',
 'tire',
 'plant',
 'Alabama',
 'returned',
 'production',
 'closed',
 'month',
 '.',
 'apparel',
 'plants',
 'specializing',
 'new',
 'styles',
 'well',
 '.',
 'Furthermore',
 ',',
 'new',
 'plants',
 'opening',
 'announced',
 'producing',
 'modular',
 'homes',
 ',',
 'metal',
 'products',
 ',',
 'chemical',
 'cellulose',
 ',',
 'travel',
 'trailers',
 ',',
 'plastics',
 '.',
 'director',
 'south',
 'Alabama',
 'reports',
 'outlook',
 'new',
 'plants',
 'plant',
 'expansion',
 'locality',
 'better',
 'time',
 'recent',
 'months',
 '.',
 'Reasons',
 'given',
 'Tennessee',
 'businessmen',
 'cautiously',
 'optimistic',
 'outlook',
 'include',
 ':',
 '``',
 'lowering',
 'interest',
 'rates',
 '``',
 ',',
 '``',
 'improving',
 'credit',
 'collections',
 '``',
 ',',
 '``',
 'increasing',
 'investment',
 'capital',
 'supply',
 'state',
 '``',
 ',',
 '``',
 'expected',
 'reversal',
 'decline',
 'national',
 'economy',
 '``',
 '.',
 'Many',
 'panelists',
 ',',
 'however',
 ',',
 'believe',
 'several',
 'months',
 'pass',
 'factors',
 'take',
 'effect',
 ',',
 'thus',
 'strong',
 'expansion',
 'occur',
 'midyear',
 'earliest',
 '.',
 'Rising',
 'costs',
 ',',
 'compared',
 'resale',
 'prices',
 ',',
 'identified',
 'panel',
 'far',
 'critical',
 'issue',
 'facing',
 'Tennessee',
 'businesses',
 'present',
 '.',
 'Low-income',
 'residential',
 'construction',
 'active',
 '.',
 'example',
 ',',
 'Birmingham',
 'Chattanooga',
 ',',
 'construction',
 'recently',
 'commenced',
 'two',
 'large',
 'residential',
 'projects',
 'low-income',
 'families',
 '.',
 'rural',
 'area',
 'Alabama',
 ',',
 '99',
 'percent',
 'homes',
 'financed',
 'Farmers',
 'Home',
 'Administration',
 'year',
 'low-price',
 'range',
 '.',
 'Last',
 'year',
 ',',
 '50',
 'percent',
 'homes',
 'similarly',
 'financed',
 'low-price',
 'range',
 '.',
 'Although',
 '235',
 'program',
 'evidently',
 'responsible',
 'many',
 'housing',
 'starts',
 ',',
 'three',
 'builders',
 'reported',
 'leaving',
 'type',
 'construction',
 'inspection',
 'regulations',
 'added',
 'costs',
 '.',
 'softening',
 'market',
 'luxury',
 'condominiums',
 'south',
 'Florida',
 ',',
 'buyers',
 'looking',
 'units',
 '$',
 '35,000',
 '.']

In [ ]:
# Count the occurrences of each word
word_counter = Counter(filtered_text_token)

# Get the most common words and their counts (e.g., top 10)
most_common_words = word_counter.most_common(25)  # Change 10 to the desired number of top words

# Print the most common words and their counts
for word, count in most_common_words:
    print(f"{word}: {count}")

,: 48
.: 45
``: 10
year: 6
construction: 5
's: 4
new: 4
plants: 4
plant: 4
Tennessee: 4
price: 4
recently: 4
paper: 4
Florida: 4
prices: 4
rates: 4
interest: 4
percent: 4
Alabama: 4
economy: 3
outlook: 3
increases: 3
large: 3
producer: 3
one: 3

In [ ]:
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer

# Download the VADER lexicon (if you haven't already)
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to C:\Users\MCOB PHD
[nltk_data]     14\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

In [ ]:
# Initialize the sentiment analyzer
analyzer = SentimentIntensityAnalyzer()

In [ ]:
# Your document, 4,400 is from Atlanta in Dec. 3, 2008 and was extremely negative sentiment
document = text_data[4400]

# Perform sentiment analysis
sentiment_scores = analyzer.polarity_scores(document)

# Interpret the sentiment scores
compound_score = sentiment_scores['compound']

if compound_score >= 0.05:
    sentiment = 'Positive'
elif compound_score <= -0.05:
    sentiment = 'Negative'
else:
    sentiment = 'Neutral'

print("Sentiment:", sentiment)
print("Compound Score:", compound_score)

Sentiment: Negative
Compound Score: -0.9442

In [ ]:
text_data[4400]

"December 3, 2008 \nEconomic conditions in the Sixth District weakened further in October through mid-November. Retail spending deteriorated, holiday sales expectations were bleak, and activity in the tourism sector declined. Residential real estate contacts indicated that sales and construction activity remained extremely weak.  Average home prices in many areas declined, pressured by the large number of foreclosed properties for sale.  Commercial contractors noted a further decline in nonresidential construction. Most manufacturing contacts noted reduced production and declines in new orders.  Credit conditions remained tight for both businesses and consumers. Labor markets weakened further and holiday-related hiring plans were restrained. Cost pressures for businesses eased on declining commodity prices and weaker demand.\nConsumer Spending and Tourism  \nDistrict retail contacts indicated that they were more pessimistic in October and early November than in the previous report. While households benefitted from declines in gasoline prices, this did not appear to be enough to boost overall retail spending. Sales activity heading into the holiday season was described as weak, and expectations for December sales were somber. The majority of retail contacts reported that inventories were above plan. In an attempt to stimulate sales, several retailers noted that they have expanded store hours, increased advertising, and plan deeper discounts. Some stores have begun to offer layaways as an incentive for budget-conscious shoppers who are unable or unwilling to use credit. Automobile dealers observed that sales deteriorated further, and that traffic was well below year-ago levels. Several dealers noted that they were trying to boost fleet and lease sales in an attempt to offset declines in the retail market.\nAfter being a relative bright spot in the District economy for most of the year, tourism activity deteriorated more recently. Reportedly, visitor numbers at tourist destinations weakened, and visitors were spending less per trip. Several cruise lines and resorts were aggressively discounting prices in an effort to boost traffic. Business travel was also down according to contacts in the convention industry.\nReal Estate and Construction\n Reports from homebuilders and Realtors indicated that new and existing home sales remained weak in October through mid-November. Many contacts reported that worsening employment conditions and the unavailability of financing was restraining sales.  However, some markets, particularly in Florida, saw modest gains in sales over weak year-ago levels.  District homebuilders continued to pull back on construction in the face of historically high inventory numbers.  Home prices continued to soften in the District with contacts indicating that the large volume of foreclosed properties for sale was exerting downward pressure on new and existing home prices.  According to District contacts, the outlook for residential sales and construction activity remains weak.  \n\tMost District commercial contractors continued to report declines in activity.  More projects were postponed or cancelled because of funding constraints and weak economic conditions.  Nonetheless, contacts also noted that more existing space had been put back into the commercial real estate market, particularly in retail. Going forward, most commercial real estate contacts anticipate softer leasing demand, while developers expect commercial construction activity to decline further.  \nManufacturing and Transportation\n  Most manufacturing contacts reported declines in production and new orders during October and early November compared with a year earlier.  The decline in production was exacerbated by a decrease in export demand. Many reports noted additional cuts to payrolls and hours, with most expecting weak conditions to persist into the new-year. Several firms remarked that they had scaled back their capital investment plans. \nTransportation contacts reported lower shipments of automotive and construction materials, far offsetting modest gains in shipments of chemicals and coal. Most contacts reported that holiday-related shipments of consumer goods were down significantly from last year. \n\tBanking and Finance\n  According to most banking contacts in the District, business and consumer lending activity decreased during October through mid-November. Credit conditions remained tight, and competition for deposits increased. Some contacts, especially in the real estate industry, observed that the restricted access to credit was forcing them out of business.  Most banking contacts indicated that they did not expect credit conditions to change materially in the near-term as banks focused on repairing their damaged balance sheets.   \n\tEmployment and Prices\n   District employment trends weakened further in October through mid-November.  Several businesses noted that layoffs accelerated and that hours declined. Retailers scaled back holiday-related hiring plans because of weak sales expectations, although the negative reports were fairly widespread across most industries. For businesses that reported they were hiring, several indicated difficulty in recruiting workers because of increasing relocation costs resulting from having to sell an existing home.\nBecause of lower input costs and weaker demand, most District contacts reported that they did not plan on raising output prices. Contacts in manufacturing, business equipment supply, and construction mentioned that costs had stabilized after a long run of increases in recent years.  Sources in the tourism industry noted difficulty raising prices because of a sharp drop in demand. Some retail and food service contacts reported a few instances of higher input costs, but also indicated that they were generally unsuccessful in passing these costs on to customers. Apart from some healthcare and other high-skilled technical positions, most contacts suggested that wage pressures continued to diminish. \n\tNatural Resources and Agriculture  Energy industry contacts reported that much of the damage that resulted from Hurricanes Ike and Gustav to the region's oil, gas, and petrochemical infrastructure had been repaired by mid-November. Total production of oil and natural gas had not returned to pre-hurricane levels, however. Falling energy prices and tight financing conditions prompted several energy industry firms to consider cutting new investment and expansion plans.\nCotton farmers reported price declines despite the smallest regional crop in 25 years, which was a result of a drop in global cotton demand.  While domestic poultry demand remained subdued, poultry producers experienced relatively strong export sales to Asia, Mexico, and Eastern Europe. \n"

# Macroeconomic variable analysis

Philadelphia Fed's coincident index

In [25]:
import pandas as pd

In [31]:
countyData = pd.read_csv('county_data.csv', encoding='latin1')

In [33]:
countyData.describe()

,FedDistrict,Pop2020,Pop2010,GDP_2021,Lat,Lon
count,3109.000000,3.109000e+03,3.109000e+03,3.109000e+03,3109.000000,3109.000000
mean,7.684143,1.054673e+05,9.878551e+04,7.425682e+06,38.460174,-92.258136
std,2.769794,3.348531e+05,3.143412e+05,3.260983e+07,5.310910,13.669657
min,1.000000,1.810000e+02,8.200000e+01,1.062500e+04,19.597764,-164.188912
25%,6.000000,1.092100e+04,1.111900e+04,4.524700e+05,34.652201,-98.317967
50%,8.000000,2.593200e+04,2.599200e+04,1.165127e+06,38.412059,-90.473868
75%,10.000000,6.934700e+04,6.709100e+04,3.392553e+06,41.858081,-83.562196
max,12.000000,9.943046e+06,9.818605e+06,8.361628e+08,69.449343,179.621188

In [34]:
countyData.head()

,State_County,County,State_abbr,State_full,County_ST,FedDistrict,Pop2020,Pop2010,GDP_2021,Lat,Lon
0,Alabama_Autauga County,Autauga,AL,Alabama,"Autauga, AL",6,56145,54571,1862747,32.532237,-86.646439
1,Alabama_Baldwin County,Baldwin,AL,Alabama,"Baldwin, AL",6,229287,182265,9891548,30.659218,-87.746067
2,Alabama_Barbour County,Barbour,AL,Alabama,"Barbour, AL",6,24589,27457,860027,31.870253,-85.405103
3,Alabama_Bibb County,Bibb,AL,Alabama,"Bibb, AL",6,22136,22915,511240,33.015893,-87.127148
4,Alabama_Blount County,Blount,AL,Alabama,"Blount, AL",6,57879,57322,1211710,33.977357,-86.566440

In [36]:
districtDiffs = pd.read_csv('district_diffs.csv', encoding='latin1')
districtLevels = pd.read_csv('district_levels.csv', encoding='latin1')

In [37]:
districtDiffs.describe()

,USPHCI,District 1,District 2,District 3,District 4,District 5,District 6,District 7,District 8,District 9,District 10,District 11,District 12
count,533.000000,533.000000,533.000000,533.000000,533.000000,533.000000,533.000000,533.000000,533.000000,533.000000,533.000000,533.000000,533.000000
mean,86.002589,1.987749,2.531107,2.205929,3.885385,0.844597,0.087580,3.863396,3.030750,2.684615,1.823865,1.443565,-0.337580
std,26.094393,5.114200,5.224089,6.253505,6.738152,3.396398,4.769787,6.625922,3.804517,3.034868,2.503767,8.737781,8.534612
min,46.140000,-13.660000,-20.980000,-20.350000,-21.010000,-3.170000,-3.990000,-23.250000,-10.000000,-8.350000,-1.820000,-8.000000,-7.000000
25%,64.050000,-0.770000,-0.840000,-3.080000,-2.350000,-1.220000,-2.790000,-2.380000,-0.530000,0.770000,-0.330000,-4.990000,-5.920000
50%,88.650000,0.330000,0.800000,1.900000,4.960000,-0.480000,-2.210000,4.750000,2.140000,1.950000,1.170000,-3.030000,-5.440000
75%,103.080000,3.240000,8.230000,7.690000,10.000000,1.520000,0.590000,10.030000,6.520000,4.010000,3.690000,9.290000,1.220000
max,138.760000,18.480000,11.540000,11.870000,16.250000,12.020000,14.800000,15.900000,11.080000,12.240000,8.690000,23.240000,23.890000

In [38]:
districtLevels.describe()

,District 1,District 2,District 3,District 4,District 5,District 6,District 7,District 8,District 9,District 10,District 11,District 12,USPHCI
count,533.000000,533.000000,533.000000,533.000000,533.000000,533.000000,533.000000,533.000000,533.000000,533.000000,533.000000,533.000000,533.000000
mean,87.990338,88.533696,88.208518,89.887974,86.847186,86.090169,89.865985,89.033340,88.687205,87.826454,87.446154,85.665009,86.002589
std,29.451564,21.688026,20.228464,19.954661,28.696872,30.056501,20.509814,22.855956,27.816459,27.340613,33.913857,33.643214,26.094393
min,46.360000,56.060000,54.540000,54.860000,45.490000,43.720000,53.890000,52.940000,47.510000,49.700000,40.480000,40.510000,46.140000
25%,62.060000,70.800000,71.620000,74.250000,62.860000,60.500000,73.430000,70.040000,64.840000,63.810000,56.990000,58.170000,64.050000
50%,87.140000,88.450000,90.310000,92.180000,86.120000,84.850000,92.260000,91.090000,88.220000,87.380000,84.430000,82.570000,88.650000
75%,104.420000,100.350000,100.210000,101.400000,104.600000,103.670000,100.220000,102.270000,106.870000,105.790000,112.370000,104.300000,103.080000
max,157.160000,135.830000,131.390000,131.870000,150.780000,153.560000,131.840000,136.930000,147.890000,145.940000,162.000000,162.260000,138.760000

In [39]:
districtLevels.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 533 entries, 0 to 532
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   DATE         533 non-null    object
 1   District 1   533 non-null    float64
 2   District 2   533 non-null    float64
 3   District 3   533 non-null    float64
 4   District 4   533 non-null    float64
 5   District 5   533 non-null    float64
 6   District 6   533 non-null    float64
 7   District 7   533 non-null    float64
 8   District 8   533 non-null    float64
 9   District 9   533 non-null    float64
 10  District 10  533 non-null    float64
 11  District 11  533 non-null    float64
 12  District 12  533 non-null    float64
 13  USPHCI       533 non-null    float64
dtypes: float64(13), object(1)
memory usage: 58.4+ KB

In [41]:
districtLevels.shape

(533, 14)

In [44]:
districtLevels.dtypes

DATE            object
District 1     float64
District 2     float64
District 3     float64
District 4     float64
District 5     float64
District 6     float64
District 7     float64
District 8     float64
District 9     float64
District 10    float64
District 11    float64
District 12    float64
USPHCI         float64
dtype: object

In [45]:
countyData['State_full'].value_counts()
# Could use this to confirm correct number of counties for each state

Texas                   254
Georgia                 159
Kentucky                120
Missouri                114
Virginia                105
Kansas                  105
Illinois                102
North Carolina          100
Iowa                     99
Tennessee                95
Nebraska                 93
Indiana                  92
Ohio                     88
Minnesota                87
Michigan                 83
Mississippi              82
Oklahoma                 77
Arkansas                 75
Wisconsin                72
Pennsylvania             67
Alabama                  67
Florida                  67
South Dakota             66
Colorado                 64
Louisiana                64
New York                 62
California               58
Montana                  56
West Virginia            55
North Dakota             53
South Carolina           46
Idaho                    44
Washington               39
Oregon                   36
New Mexico               33
Utah                     29
Alaska                   28
Maryland                 23
Wyoming                  23
New Jersey               21
Nevada                   16
Maine                    16
Arizona                  15
Vermont                  14
Massachusetts            14
New Hampshire            10
Connecticut               8
Rhode Island              5
Hawaii                    4
Delaware                  3
District of Columbia      1
Name: State_full, dtype: int64

In [48]:
print(countyData['State_full'].unique())
print(countyData['State_full'].nunique())

['Alabama' 'Alaska' 'Arizona' 'Arkansas' 'California' 'Colorado'
 'Connecticut' 'Delaware' 'District of Columbia' 'Florida' 'Georgia'
 'Hawaii' 'Idaho' 'Illinois' 'Indiana' 'Iowa' 'Kansas' 'Kentucky'
 'Louisiana' 'Maine' 'Maryland' 'Massachusetts' 'Michigan' 'Minnesota'
 'Mississippi' 'Missouri' 'Montana' 'Nebraska' 'Nevada' 'New Hampshire'
 'New Jersey' 'New Mexico' 'New York' 'North Carolina' 'North Dakota'
 'Ohio' 'Oklahoma' 'Oregon' 'Pennsylvania' 'Rhode Island' 'South Carolina'
 'South Dakota' 'Tennessee' 'Texas' 'Utah' 'Vermont' 'Virginia'
 'Washington' 'West Virginia' 'Wisconsin' 'Wyoming']
51

In [49]:
districtDiffs.corr()
# When compared with districtLevels, shows how subtracting the national score reduces the correlation

,USPHCI,District 1,District 2,District 3,District 4,District 5,District 6,District 7,District 8,District 9,District 10,District 11,District 12
USPHCI,1.000000,0.600674,-0.872355,-0.952415,-0.933104,0.739378,0.802336,-0.879609,-0.871288,0.527998,0.461648,0.861560,0.848899
District 1,0.600674,1.000000,-0.185353,-0.462035,-0.489717,0.866389,0.838006,-0.431276,-0.365569,0.812713,0.736030,0.725606,0.862789
District 2,-0.872355,-0.185353,1.000000,0.935636,0.873151,-0.449596,-0.540284,0.840949,0.835550,-0.223385,-0.234196,-0.687531,-0.560027
District 3,-0.952415,-0.462035,0.935636,1.000000,0.973748,-0.685088,-0.756573,0.944554,0.902328,-0.425369,-0.484630,-0.883548,-0.786261
District 4,-0.933104,-0.489717,0.873151,0.973748,1.000000,-0.670061,-0.736710,0.985654,0.959230,-0.360173,-0.457039,-0.885986,-0.786304
District 5,0.739378,0.866389,-0.449596,-0.685088,-0.670061,1.000000,0.968969,-0.633263,-0.495031,0.852078,0.849830,0.896532,0.961552
District 6,0.802336,0.838006,-0.540284,-0.756573,-0.736710,0.968969,1.000000,-0.692193,-0.562189,0.828880,0.819842,0.910071,0.979762
District 7,-0.879609,-0.431276,0.840949,0.944554,0.985654,-0.633263,-0.692193,1.000000,0.966038,-0.303721,-0.447896,-0.874394,-0.744501
District 8,-0.871288,-0.365569,0.835550,0.902328,0.959230,-0.495031,-0.562189,0.966038,1.000000,-0.177588,-0.266863,-0.770148,-0.645807
District 9,0.527998,0.812713,-0.223385,-0.425369,-0.360173,0.852078,0.828880,-0.303721,-0.177588,1.000000,0.851413,0.696903,0.803439
District 10,0.461648,0.736030,-0.234196,-0.484630,-0.457039,0.849830,0.819842,-0.447896,-0.266863,0.851413,1.000000,0.801229,0.794702
District 11,0.861560,0.725606,-0.687531,-0.883548,-0.885986,0.896532,0.910071,-0.874394,-0.770148,0.696903,0.801229,1.000000,0.936054
District 12,0.848899,0.862789,-0.560027,-0.786261,-0.786304,0.961552,0.979762,-0.744501,-0.645807,0.803439,0.794702,0.936054,1.000000

In [51]:
districtDiffs.head()

,Date,USPHCI,District 1,District 2,District 3,District 4,District 5,District 6,District 7,District 8,District 9,District 10,District 11,District 12
0,4/1/1979,46.14,0.22,9.92,11.87,16.25,-0.15,-2.42,15.90,11.08,4.86,3.98,-5.66,-5.63
1,5/1/1979,46.37,0.22,9.82,11.79,16.14,-0.24,-2.51,15.80,10.93,4.79,3.90,-5.73,-5.70
2,6/1/1979,46.50,0.30,9.79,11.79,16.09,-0.27,-2.53,15.70,10.83,4.76,3.86,-5.71,-5.65
3,7/1/1979,46.62,0.28,9.66,11.69,15.90,-0.29,-2.62,15.49,10.62,4.65,3.81,-5.67,-5.62
4,8/1/1979,46.68,0.43,9.67,11.62,15.83,-0.32,-2.54,15.23,10.52,4.59,3.83,-5.57,-5.60

In [50]:
districtLevels.corr()

,District 1,District 2,District 3,District 4,District 5,District 6,District 7,District 8,District 9,District 10,District 11,District 12,USPHCI
District 1,1.000000,0.997591,0.991818,0.987138,0.995845,0.995676,0.983998,0.991567,0.995445,0.994338,0.991119,0.996918,0.990316
District 2,0.997591,1.000000,0.996427,0.990505,0.995455,0.994680,0.986975,0.992750,0.995005,0.993478,0.988487,0.995106,0.993042
District 3,0.991818,0.996427,1.000000,0.997062,0.993084,0.991447,0.994391,0.995954,0.993882,0.990988,0.981981,0.988305,0.995551
District 4,0.987138,0.990505,0.997062,1.000000,0.990237,0.988778,0.998796,0.997502,0.993212,0.988507,0.976934,0.984134,0.992600
District 5,0.995845,0.995455,0.993084,0.990237,1.000000,0.999395,0.985632,0.996427,0.998494,0.999037,0.996170,0.997844,0.996820
District 6,0.995676,0.994680,0.991447,0.988778,0.999395,1.000000,0.984373,0.995792,0.998238,0.998745,0.995898,0.998538,0.995504
District 7,0.983998,0.986975,0.994391,0.998796,0.985632,0.984373,1.000000,0.995554,0.989535,0.983618,0.969930,0.979378,0.988121
District 8,0.991567,0.992750,0.995954,0.997502,0.996427,0.995792,0.995554,1.000000,0.997500,0.995427,0.987260,0.991620,0.996658
District 9,0.995445,0.995005,0.993882,0.993212,0.998494,0.998238,0.989535,0.997500,1.000000,0.998479,0.993947,0.996539,0.995698
District 10,0.994338,0.993478,0.990988,0.988507,0.999037,0.998745,0.983618,0.995427,0.998479,1.000000,0.997653,0.997053,0.996695
District 11,0.991119,0.988487,0.981981,0.976934,0.996170,0.995898,0.969930,0.987260,0.993947,0.997653,1.000000,0.995835,0.991409
District 12,0.996918,0.995106,0.988305,0.984134,0.997844,0.998538,0.979378,0.991620,0.996539,0.997053,0.995835,1.000000,0.990970
USPHCI,0.990316,0.993042,0.995551,0.992600,0.996820,0.995504,0.988121,0.996658,0.995698,0.996695,0.991409,0.990970,1.000000

In [52]:
districtDiffs['Date'] = pd.to_datetime(districtDiffs['Date'])

In [53]:
districtDiffs.dtypes

Date           datetime64[ns]
USPHCI                float64
District 1            float64
District 2            float64
District 3            float64
District 4            float64
District 5            float64
District 6            float64
District 7            float64
District 8            float64
District 9            float64
District 10           float64
District 11           float64
District 12           float64
dtype: object

In [55]:
districtDiffs.set_index('Date', inplace=True)

In [56]:
# Resample the data into quarterly intervals and use the sum function to aggregate
quarterly_data = districtDiffs.resample('Q').sum()

In [57]:
quarterly_data.describe()

,USPHCI,District 1,District 2,District 3,District 4,District 5,District 6,District 7,District 8,District 9,District 10,District 11,District 12
count,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000
mean,257.524607,5.952079,7.579101,6.605393,11.634326,2.529045,0.262247,11.568483,9.075225,8.038764,5.461348,4.322584,-1.010843
std,77.762311,15.210051,15.666683,18.756192,20.205684,10.114373,14.226573,19.865853,11.407695,9.034302,7.477658,26.120942,25.496394
min,139.010000,-36.110000,-54.380000,-57.130000,-49.570000,-9.420000,-11.850000,-58.010000,-20.240000,-15.010000,-5.100000,-23.820000,-20.890000
25%,192.285000,-2.345000,-2.720000,-9.282500,-7.302500,-3.620000,-8.327500,-7.295000,-1.625000,2.305000,-1.007500,-15.015000,-17.735000
50%,266.030000,0.975000,2.415000,5.480000,14.355000,-1.505000,-6.575000,13.890000,6.330000,5.780000,3.555000,-9.050000,-16.320000
75%,307.342500,9.695000,24.265000,22.937500,30.067500,4.635000,1.870000,30.145000,19.505000,12.205000,11.137500,27.890000,3.870000
max,413.830000,51.830000,34.340000,35.450000,48.480000,33.020000,43.780000,47.400000,32.840000,35.840000,25.810000,68.760000,71.230000

In [58]:
quarterly_data.reset_index(inplace=True)

In [59]:
quarterly_data.describe()

,USPHCI,District 1,District 2,District 3,District 4,District 5,District 6,District 7,District 8,District 9,District 10,District 11,District 12
count,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000
mean,257.524607,5.952079,7.579101,6.605393,11.634326,2.529045,0.262247,11.568483,9.075225,8.038764,5.461348,4.322584,-1.010843
std,77.762311,15.210051,15.666683,18.756192,20.205684,10.114373,14.226573,19.865853,11.407695,9.034302,7.477658,26.120942,25.496394
min,139.010000,-36.110000,-54.380000,-57.130000,-49.570000,-9.420000,-11.850000,-58.010000,-20.240000,-15.010000,-5.100000,-23.820000,-20.890000
25%,192.285000,-2.345000,-2.720000,-9.282500,-7.302500,-3.620000,-8.327500,-7.295000,-1.625000,2.305000,-1.007500,-15.015000,-17.735000
50%,266.030000,0.975000,2.415000,5.480000,14.355000,-1.505000,-6.575000,13.890000,6.330000,5.780000,3.555000,-9.050000,-16.320000
75%,307.342500,9.695000,24.265000,22.937500,30.067500,4.635000,1.870000,30.145000,19.505000,12.205000,11.137500,27.890000,3.870000
max,413.830000,51.830000,34.340000,35.450000,48.480000,33.020000,43.780000,47.400000,32.840000,35.840000,25.810000,68.760000,71.230000